import './style.css';


export default function Footer () {
    return (
        <div>
        <div className='wrapper'>
            <h2>Советы перед покупкой кроссовок</h2>
            <ul className='advice'>
                <li>Кроссовки для бега лучше покупать во второй половине дня</li>
                <li>Кроссовки для бега лучше покупать на размер больше</li>
                <li>Протестируйте кроссовки в магазине перед покупкой</li>
            </ul>
            <p className='quote'>«Бег — это большой знак вопроса. Каждый день он спрашивает вас: «Кем ты будешь сегодня — слабаком или волевым человеком?».</p>
        </div>
        <div className='footer'>
            <div className='signature'>
                <span>Made with ❤️ at nFactorial in 2023.</span>
            </div>
            <div className='signature1'>
                <span> ⭐️ All images are generated by Midjourney</span>
            </div>
        </div>
        </div>
    
    )
}
